name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.15.0"
          cache: npm

      - name: Install dependencies
        run: npm install

      # - name: Prettify code
      #   uses: creyD/prettier_action@v4.3
      #   with:
      #     prettier_options: --write .

      # - name: Build project
      #   run: npm run build:dev
      #   env:
      #     GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Start server
        run: npm run dev &
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Run end-to-end tests
        run: npm run ci:cypress:e-to-e

      # - name: Run component tests
      #   run: npm run ci:cypress:component
      #   env:
      #     GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      # - name: Run Lighthouse tests
      #   run: npm run lighthouse
