name: CI

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.17.0"
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Set Up TOML file
        run: echo "[vars] \n GOOGLE_API_KEY=\"${{ secrets.GOOGLE_API_KEY }}\"" > wrangler.toml

      - name: Build project
        run: npm run pages:build

      - name: Start server
        run: npm run pages:serve &

      - name: Run end-to-end tests
        run: npm run ci:cypress:e-to-e

      # - name: Run component tests
      #   run: npm run ci:cypress:component
      #   env:
      #     GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      # - name: Run Lighthouse tests
      #   run: npm run lighthouse
