name: CI

on:
  pull_request:
  push:
    branches:
      - main
      - development

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.15.0"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: nmp run build

      - name: Start server
        run: npm run start &

      - name: Run end-to-end tests
        run: npm run ci:cypress
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        with:
          wait-on: 'http://localhost:3000'

      # - name: Run component tests
      #   run: npm run ci:cypress:component
      #   env:
      #     GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      # - name: Run Lighthouse tests
      #   run: npm run lighthouse